name: app

type: nodejs:12

web:
    commands:
      # Run a no-op process that uses no CPU resources, since this is a static site.
        start: sleep infinity
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: ''
            passthru: '/index.html'
            index:
                - 'index.html'
            allow: true
            expires: 24h

hooks:
    build: |
        curl -sS https://platform.sh/cli/installer | php

crons:
    backup:
        spec: '*/10 * * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform backup:create --yes --no-wait
            fi

    testcron:
        spec: '* * * * *'
        cmd: |
            echo 'cron running...'
            echo ${TESTVAR1}
