name: app

type: nodejs:12

web:
    commands:
      # Run a no-op process that uses no CPU resources, since this is a static site.
        start: sleep infinity
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: ''
            passthru: false
            index:
                - 'index.html'
            scripts: false
            allow: true
            expires: 24h
